var http = require('http')
var fs = require('fs')
var axios = require('axios')
var url = require('url')

function geraIndexFilmes(index){
    var indexHTML = `
        <!DOCTYPE html>
        <html lang="pt-br">
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Página Filmes</title>
            <style>
                body {
                    font-family: 'Arial', sans-serif;
                }
                h3 {
                    color: #607D8B;
                }
                ul {
                    list-style-type: none;
                    padding: 0;
                }
                li {
                    margin-bottom: 10px;
                }
                h5 {
                    color: #607D8B;
                }
            </style>
        </head>
        <body>
            <div>
                <h3>Filmes</h3>
                <ul>
    `            
    
    index.forEach(filme => {
        indexHTML += `
        <li>
        <a href="/filmes/${filme._id}">${filme.title}</a>
        </li>
        `
    });
    
    indexHTML += `</ul>
                <h5>Generated by MovieApp::EngWeb2024::A100555</h5>
            </div>
        </body>
        </html>
    `

    return indexHTML
}

function geraPagFilme(filme){
    var pagHTML = `
    <!DOCTYPE html> 
    <html lang="pt-br">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Filme: ${filme[0].title}</title>
        <link rel="stylesheet" href="../w3.css">
        <style>
            body {{
                font-family: Arial, sans-serif;
            }}
            .w3-card-4 {{
                max-width: 600px;
                margin: 50px auto;
                padding: 20px;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            }}
            .w3-container-header, .w3-container-footer {{
                background-color: #607D8B;
                color: #fff;
                text-align: center;
                padding: 10px;
            }}
            .w3-container-content {{
                padding: 20px;
            }}
        </style>
    </head>

    <body>

        <div class="w3-card-4">

            <header class="w3-container w3-container-header">
                <h2>Filme: ${filme[0].title}</h2>
            </header>

            <div class="w3-container w3-container-content">
                <table class="w3-table w3-striped">
                    <tr>
                        <td><b>Id</b></td>
                        <td>${filme[0]._id}</td>
                    </tr>
                    <tr>
                        <td><b>Ano</b></td>
                        <td>${filme[0].year}</td>
                    </tr>
                    <tr>
                        <td><b>Elenco</b></td>
                        <td>${filme[0].cast}</td>
                    </tr>
                    <tr>
                        <td><b>Géneros</b></td>
                        <td>${filme[0].genres}</td>
                    </tr>
                </table>
            </div>

            <footer class="w3-container w3-container-footer">
                <p>Generated by MovieApp::EngWeb2024::A100555</p>
                <p>
                    <a href="http://localhost:7777/filmes">Voltar à página de filmes</a>
                </p>
            </footer>

        </div>

    </body>

    </html>
    `
    return pagHTML
}

function geraIndexAtores(index){
    var indexHTML = `
    <!DOCTYPE html>
    <html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Página Atores</title>
        <style>
            body {
                font-family: 'Arial', sans-serif;
            }
            h3 {
                color: #607D8B;
            }
            ul {
                list-style-type: none;
                padding: 0;
            }
            li {
                margin-bottom: 10px;
            }
            h5 {
                color: #607D8B;
            }
        </style>
    </head>
    <body>
        <div>
            <h3>Atores</h3>
            <ul>
    `            

    index.forEach(ator => {
        indexHTML += `
        <li>
        <a href="/atores/${ator.id}">${ator.nome}</a>
        </li>
        `
    });

    indexHTML += `</ul>
                <h5>Generated by MovieApp::EngWeb2024::A100555</h5>
            </div>
        </body>
        </html>
    `

    return indexHTML
}

function geraIndexGeneros(index){
    var indexHTML = `
    <!DOCTYPE html>
    <html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Página Generos</title>
        <style>
            body {
                font-family: 'Arial', sans-serif;
            }
            h3 {
                color: #607D8B;
            }
            ul {
                list-style-type: none;
                padding: 0;
            }
            li {
                margin-bottom: 10px;
            }
            h5 {
                color: #607D8B;
            }
        </style>
    </head>
    <body>
        <div>
            <h3>Generos</h3>
            <ul>
    `            

    index.forEach(genero => {
        indexHTML += `
        <li>
        <a href="/generos/${genero.id}">${genero.nome}</a>
        </li>
        `
    });

    indexHTML += `</ul>
                <h5>Generated by MovieApp::EngWeb2024::A100555</h5>
            </div>
        </body>
        </html>
    `

    return indexHTML
}

function contemGenero(lista,genero){
    for (let i = 0; i < lista.length; i++) {
        if(lista[i] == genero){
            return true
        }
    }
    return false
}

function geraIndexFG(filmes,genero){
    var indexHTML = `
        <!DOCTYPE html>
        <html lang="pt-br">
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Página Filmes por Genero</title>
            <style>
                body {
                    font-family: 'Arial', sans-serif;
                }
                h3 {
                    color: #607D8B;
                }
                ul {
                    list-style-type: none;
                    padding: 0;
                }
                li {
                    margin-bottom: 10px;
                }
                h5 {
                    color: #607D8B;
                }
            </style>
        </head>
        <body>
            <div>
                <h3>Filmes por Género: ${genero[0].nome}</h3>
                <ul>
    `            
    
    filmes.forEach(filme => {
        if (filme.genres[0]) {
            if(contemGenero(filme.genres,genero[0].nome)){
                indexHTML += `
                <li>
                <a href="/filmes/${filme._id}">${filme.title}</a>
                </li>    `
            } 
        } else {
        }   
    });
    
    indexHTML += `</ul>
                <h5>Generated by MovieApp::EngWeb2024::A100555</h5>
            </div>
        </body>
        </html>
    `

    return indexHTML
}

http.createServer((req,res) => {
    console.log(req.method + ' ' + req.url)
    var q = url.parse(req.url).pathname
    var regex_filmes = /\/filmes\/(f\d{1,5})/
    var regex_atores = /\/atores\/(a\d{1,5})/
    var regex_generos = /\/generos\/(g\d{1,2})/

    if(q == '/'){
        res.writeHead(200, {'Content-Type' : 'text/html; charset=utf-8'})
        res.write('<h1> Página Inicial </h1>')
        res.end()
    }else if (q == '/filmes'){
        axios.get("http://localhost:3000/ocorrencias")
        .then(resp => {
            res.writeHead(200, {'Content-Type' : 'text/html; charset=utf-8'})
            res.write(geraIndexFilmes(resp.data))
            res.end()
        })
        .catch(erro =>{
            res.writeHead(500, {'Content-Type' : 'text/html; charset=utf-8'})
            res.write("<p> Ocorreu um erro: " + erro + "</p>")
            res.end()
        })
    }else if (test = regex_filmes.exec(q)){
        axios.get("http://localhost:3000/ocorrencias?_id=" + test[1])
        .then(resp =>{
            res.writeHead(200, {'Content-Type' : 'text/html; charset=utf-8'})
            res.write(geraPagFilme(resp.data))
            res.end()
        })
        .catch(erro =>{
            res.writeHead(500, {'Content-Type' : 'text/html; charset=utf-8'})
            res.write("<p> Ocorreu um erro: " + erro + "</p>")
            res.end()
        })
    }else if (q == '/atores'){
        axios.get("http://localhost:3000/atores")
        .then(resp => {
            res.writeHead(200, {'Content-Type' : 'text/html; charset=utf-8'})
            res.write(geraIndexAtores(resp.data))
            res.end()
        })
        .catch(erro =>{
            res.writeHead(500, {'Content-Type' : 'text/html; charset=utf-8'})
            res.write("<p> Ocorreu um erro: " + erro + "</p>")
            res.end()
        })
    }else if (test2 = regex_atores.exec(q)){
        axios.get("http://localhost:3000/atores?id=" + test2[1])
        .then(resp => {
            res.writeHead(200, {'Content-Type' : 'text/html; charset=utf-8'})
            res.write('<p> Id: ' + resp.data[0].id + '</p><p> Nome: ' + resp.data[0].nome + '</p>')
            res.end()
        })
        .catch(erro =>{
            res.writeHead(500, {'Content-Type' : 'text/html; charset=utf-8'})
            res.write("<p> Ocorreu um erro: " + erro + "</p>")
            res.end()
        })
    }else if (q == '/generos'){
        axios.get("http://localhost:3000/generos")
        .then(resp => {
            res.writeHead(200, {'Content-Type' : 'text/html; charset=utf-8'})
            res.write(geraIndexGeneros(resp.data))
            res.end()
        })
        .catch(erro =>{
            res.writeHead(500, {'Content-Type' : 'text/html; charset=utf-8'})
            res.write("<p> Ocorreu um erro: " + erro + "</p>")
            res.end()
        })
    }else if (test3 = regex_generos.exec(q)){
        axios.get("http://localhost:3000/ocorrencias")
        .then(resp => {
            axios.get("http://localhost:3000/generos?id=" + test3[1])
            .then(resp2 => {
                res.writeHead(200, {'Content-Type' : 'text/html; charset=utf-8'})
                res.write(geraIndexFG(resp.data,resp2.data))
                res.end()
            })
            .catch(erro =>{
                res.writeHead(500, {'Content-Type' : 'text/html; charset=utf-8'})
                res.write("<p> Ocorreu um erro: " + erro + "</p>")
                res.end()
            })
        })
        .catch(erro =>{
            res.writeHead(500, {'Content-Type' : 'text/html; charset=utf-8'})
            res.write("<p> Ocorreu um erro: " + erro + "</p>")
            res.end()
        })
    }else if (q == '/w3.css'){
        fs.readFile("w3.css", (erro,dados) => {
            res.writeHead(200, {'Content-Type' : 'text/css; charset=utf-8'})
            res.write(dados)
            res.end()
        })
    }else{
        res.writeHead(400, {'Content-Type' : 'text/html; charset=utf-8'})
        res.write('<p> Erro: Pedido não suportado </p>')
        res.write('<pre>' + req.url +'</pre>')
        res.end()
    }
}).listen(7777)