import json

with open('mapa-virtual.json', 'r', encoding='utf-8') as f:
    bd = json.load(f)

for city in bd['cidades']:
    with open(f'cidades/{str(city["id"])}.html', 'w', encoding='utf-8') as f:
        pagHTML = f"""
        <!DOCTYPE html> 
        <html lang="pt-br">

        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Cidade: {city['nome']}</title>
            <link rel="stylesheet" href="w3.css">
            <style>
                body {{
                    font-family: Arial, sans-serif;
                }}
                .w3-card-4 {{
                    max-width: 600px;
                    margin: 50px auto;
                    padding: 20px;
                    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
                }}
                .w3-container-header, .w3-container-footer {{
                    background-color: #607D8B;
                    color: #fff;
                    text-align: center;
                    padding: 10px;
                }}
                .w3-container-content {{
                    padding: 20px;
                }}
            </style>
        </head>

        <body>

            <div class="w3-card-4">

                <header class="w3-container w3-container-header">
                    <h2>Cidade: {city['nome']}</h2>
                </header>

                <div class="w3-container w3-container-content">
                    <table class="w3-table w3-striped">
                        <tr>
                            <td><b>Id</b></td>
                            <td>{city['id']}</td>
                        </tr>
                        <tr>
                            <td><b>Distrito</b></td>
                            <td>{city['distrito']}</td>
                        </tr>
                        <tr>
                            <td><b>População</b></td>
                            <td>{city['população']}</td>
                        </tr>
                        <tr>
                            <td><b>Descrição</b></td>
                            <td>{city['descrição']}</td>
                        </tr>
                    </table>

                    <header class="w3-container w3-container-header">
                        <h4>Ligações: <!-- OUTRAS_CIDADES --></h4>
                    </header>
                </div>

                <footer class="w3-container w3-container-footer">
                    <p>Generated by CityApp::EngWeb2024::A100555</p>
                    <p>
                        <a href="http://localhost:7777/">Voltar à página principal</a>
                    </p>
                </footer>

            </div>

        </body>

        </html>
        """
        f.write(pagHTML)