import parse

def chaveOrd(rua):
    return rua['meta']['nome']

#bd = parse.parse("/home/rod/Desktop/EngWeb2024/TPC1/MapaRuas-materialBase/texto")
bd = parse.parse('C:/Users/Utilizador/Desktop/UM/EngWeb2024/TPC1/MapaRuas-materialBase/texto')

bd.sort(key=chaveOrd)

preHTML = f"""
<!DOCTYPE html>
<html>

    <head>
        <title>Lista de Ruas de Braga</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8"/> 
        <link rel="stylesheet" href="w3.css">
        <style> button{{margin: 8px;}}  a{{text-decoration: none;}} body {{text-align: center; background-size:cover; background-image: url('bgi.jpg');}} 
        div{{width: 650px;
            height: 900px; 
            overflow: auto;
            scrollbar-width: thin; 
            scrollbar-color: transparent transparent;
            border: 1px solid #ccc;
            padding: 10px;
            margin:auto;}}</style>
    </head>

<body>

    <div class="w3-card-4">
        
        <header class="w3-container w3-blue-gray">
          <h3>Lista de Ruas de Braga</h3>
        </header>
        
        <div class="w3-container">
"""

posHTML = f"""
        </div>
        
        <footer class="w3-container w3-red">
            <h5>Generated by RodEnterprises::EngWeb2024::A100555 </h5>
        </footer>        
    </div> 

</body>

</html>
"""

conteudo = ""

for e in bd:
    conteudo += f"""
        <a href="MRB-{e['meta']['número']}.html">
            <button class="w3-button w3-blue-gray w3-border w3-border-black w3-round-xxlarge w3-hover-teal w3-padding-16 ">
                {e['meta']['nome']}
            </button> <br>
        </a>
    """
    
pagHTML = preHTML + conteudo + posHTML
f = open("MRBSite/index.html", 'w',encoding='utf-8')
f.write(pagHTML)
f.close()