import parse
import os

bd = parse.parse("/home/rod/Desktop/EngWeb2024/TPC1/MapaRuas-materialBase/texto")
#bd = parse.parse('C:/Users/Utilizador/Desktop/UM/EngWeb2024/TPC1/MapaRuas-materialBase/texto')

for e in bd:
    f = open('MRBSite/MRB-'+str(e['meta']['número'])+'.html', 'w', encoding='utf-8')
    preHTML = f"""
    <!DOCTYPE html> 
    <html>

        <head>
            <title>Rua {e['meta']['número']}</title>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta charset="utf-8"/> 
            <link rel="stylesheet" href="w3.css"> 
        </head>

    <body>

        <div class="w3-container">
        </div>

        <div class="w3-bar w3-blue-gray">
        <button class="w3-bar-item w3-button" onclick="openTab('London')">Imagens</button>
        <button class="w3-bar-item w3-button" onclick="openTab('Paris')">Casas</button>
        <button class="w3-bar-item w3-button" onclick="openTab('Tokyo')">Descrição</button>
        </div>

        <div id="London" class="w3-container city">
    """
    imgs = "<h2>Esquiços</h2>"

    for img in e['figura']:
        imgs += f"""
            <img src={'../MapaRuas-materialBase/imagem/' + img['path']} class="w3-round-large" alt={img['id']} style="width:100%">
            <p>{img['legenda']} </p>
            <br>
        """
    imgs += "<br> <h2>Atualidade</h2>"
    
    dir = os.getcwd()
    
    for img in os.listdir(os.chdir('./MapaRuas-materialBase/atual/')):
        if img.startswith(e['meta']['número'] + '-') and img.endswith(".JPG"):
            imgs += f"""
                <img src={os.path.abspath(img)} class="w3-round-large w3-padding-32 w3-margin" style="width:40%">
            """
    
    os.chdir(dir)
        
    midHTML1 = f"""
        </div>

        <div id="Paris" class="w3-container city" style="display:none">
        <h2>Casas</h2>

    """
    
    casas = ""
    
    if e['lista-casas']:
        i = 0
        for casa in e['lista-casas']:
            casas += f"""
            <ul class="w3-ul w3-card-4" style="width:100%">
                <li><b>Número</b> -> {casa['número']}</li>
                <li><b>Enfiteuta</b> -> {casa['enfiteuta']}</li>
                <li><b>Foro</b> -> {casa['foro']}</li>
                <li><b>Vista</b> -> {casa['vista']}</li>
                <li><b>Descrição</b> -> {casa['desc'][0]['para']}</li>
            </ul>
            <br>
            """
        
    midHTML2 = f"""
        </div>

        <div id="Tokyo" class="w3-container city" style="display:none">
            <h2>Descrição da Rua</h2>
    """
    desc = ""
    
    for d in e['para']:
        desc += f"""
            <div class="w3-panel w3-light-gray">
                <p>{d['para']}</p>
            </div>
        """

    posHTML = f"""
        </div>
        <script>
        function openTab(cityName) {{
        var i;
        var x = document.getElementsByClassName("city");
        for (i = 0; i < x.length; i++) {{
            x[i].style.display = "none";  
        }}
        document.getElementById(cityName).style.display = "block";  
        }}
        </script>
        
        <footer class="w3-container w3-red">
            <h5>Generated by RodEnterprises::EngWeb2024::A100555 </h5>
            <address>
                <a href="index.html">Volar à página inicial</a>
            </address>
        </footer> 

    </body>

    </html>
    """
    
    pagHTML = preHTML + imgs + midHTML1 + casas + midHTML2 + desc + posHTML
    f.write(pagHTML)
    f.close()